#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NavigationDrawer.Resource", IsApplication=true)]

namespace NavigationDrawer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0b0000
			public const int drawer_items_array = 2131427328;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f01000a
			public const int fastScrollEnabled = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int fastScrollHorizontalThumbDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fastScrollHorizontalTrackDrawable = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int fastScrollVerticalThumbDrawable = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int fastScrollVerticalTrackDrawable = 2130771980;
			
			// aapt resource value: 0x7f010016
			public const int font = 2130771990;
			
			// aapt resource value: 0x7f01000f
			public const int fontProviderAuthority = 2130771983;
			
			// aapt resource value: 0x7f010012
			public const int fontProviderCerts = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int fontProviderFetchStrategy = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int fontProviderFetchTimeout = 2130771988;
			
			// aapt resource value: 0x7f010010
			public const int fontProviderPackage = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int fontProviderQuery = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int fontStyle = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int fontWeight = 2130771991;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int layoutManager = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int reverseLayout = 2130771976;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int spanCount = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int stackFromEnd = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f0a0000
			public const int abc_action_bar_embed_tabs = 2131361792;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_dark = 2130968591;
			
			// aapt resource value: 0x7f040000
			public const int common_google_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int common_google_signin_btn_text_dark_disabled = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int common_google_signin_btn_text_dark_focused = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_google_signin_btn_text_dark_pressed = 2130968579;
			
			// aapt resource value: 0x7f040010
			public const int common_google_signin_btn_text_light = 2130968592;
			
			// aapt resource value: 0x7f040004
			public const int common_google_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int common_google_signin_btn_text_light_disabled = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_light_focused = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_light_pressed = 2130968583;
			
			// aapt resource value: 0x7f040011
			public const int common_google_signin_btn_tint = 2130968593;
			
			// aapt resource value: 0x7f04000b
			public const int notification_action_color_filter = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int notification_icon_bg_color = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int notification_material_background_media_default_color = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int primary_text_default_material_dark = 2130968585;
			
			// aapt resource value: 0x7f04000d
			public const int ripple_material_light = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int secondary_text_default_material_dark = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int secondary_text_default_material_light = 2130968590;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f07000a
			public const int compat_button_inset_horizontal_material = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int compat_button_inset_vertical_material = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int compat_button_padding_horizontal_material = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int compat_button_padding_vertical_material = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int compat_control_corner_material = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int fastscroll_default_thickness = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int fastscroll_margin = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int fastscroll_minimum_range = 2131165186;
			
			// aapt resource value: 0x7f07001f
			public const int horizontal_page_margin = 2131165215;
			
			// aapt resource value: 0x7f070003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int item_touch_helper_swipe_escape_velocity = 2131165189;
			
			// aapt resource value: 0x7f07001e
			public const int margin_huge = 2131165214;
			
			// aapt resource value: 0x7f07001d
			public const int margin_large = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int margin_medium = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int margin_small = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int margin_tiny = 2131165210;
			
			// aapt resource value: 0x7f07000f
			public const int notification_action_icon_size = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int notification_action_text_size = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int notification_big_circle_margin = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int notification_content_margin_start = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int notification_large_icon_height = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int notification_large_icon_width = 2131165203;
			
			// aapt resource value: 0x7f070008
			public const int notification_main_column_padding_top = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int notification_media_narrow_margin = 2131165193;
			
			// aapt resource value: 0x7f070014
			public const int notification_right_icon_size = 2131165204;
			
			// aapt resource value: 0x7f070006
			public const int notification_right_side_padding_top = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int notification_small_icon_background_padding = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int notification_small_icon_size_as_large = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int notification_subtext_size = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int notification_top_pad = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int notification_top_pad_large_text = 2131165209;
			
			// aapt resource value: 0x7f070020
			public const int vertical_page_margin = 2131165216;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int borderless_rounded = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_full_open_on_phone = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_focused = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_normal_background = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_normal_background = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_normal_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Drawer = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int drawer_shadow = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Exit = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int googleg_disabled_color_18 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int googleg_standard_color_18 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int greentick = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_drawer = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_launcher = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Notification = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_action_background = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_bg = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notification_bg_low = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_bg_low_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int notification_bg_low_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notification_bg_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int notification_bg_normal_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int notification_icon_background = 2130837541;
			
			// aapt resource value: 0x7f02002b
			public const int notification_template_icon_bg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int notification_template_icon_low_bg = 2130837548;
			
			// aapt resource value: 0x7f020026
			public const int notification_tile_bg = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int notify_panel_notification_icon_bg = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Refresh = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int sample_dashboard_item_background = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int tile = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08002b
			public const int action0 = 2131230763;
			
			// aapt resource value: 0x7f080028
			public const int action_container = 2131230760;
			
			// aapt resource value: 0x7f08002f
			public const int action_divider = 2131230767;
			
			// aapt resource value: 0x7f080029
			public const int action_image = 2131230761;
			
			// aapt resource value: 0x7f08003c
			public const int action_refresh = 2131230780;
			
			// aapt resource value: 0x7f08002a
			public const int action_text = 2131230762;
			
			// aapt resource value: 0x7f080039
			public const int actions = 2131230777;
			
			// aapt resource value: 0x7f080006
			public const int adjust_height = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int adjust_width = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int async = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int auto = 2131230732;
			
			// aapt resource value: 0x7f080010
			public const int blocking = 2131230736;
			
			// aapt resource value: 0x7f080017
			public const int btnLogin = 2131230743;
			
			// aapt resource value: 0x7f080021
			public const int btnSendResponse = 2131230753;
			
			// aapt resource value: 0x7f08002c
			public const int cancel_action = 2131230764;
			
			// aapt resource value: 0x7f080034
			public const int chronometer = 2131230772;
			
			// aapt resource value: 0x7f080019
			public const int content_frame = 2131230745;
			
			// aapt resource value: 0x7f08000d
			public const int dark = 2131230733;
			
			// aapt resource value: 0x7f080018
			public const int drawer_layout = 2131230744;
			
			// aapt resource value: 0x7f08003b
			public const int end_padder = 2131230779;
			
			// aapt resource value: 0x7f080020
			public const int etAnswer = 2131230752;
			
			// aapt resource value: 0x7f080011
			public const int forever = 2131230737;
			
			// aapt resource value: 0x7f080036
			public const int icon = 2131230774;
			
			// aapt resource value: 0x7f08003a
			public const int icon_group = 2131230778;
			
			// aapt resource value: 0x7f080009
			public const int icon_only = 2131230729;
			
			// aapt resource value: 0x7f080025
			public const int image = 2131230757;
			
			// aapt resource value: 0x7f080022
			public const int imgResponseTick = 2131230754;
			
			// aapt resource value: 0x7f080035
			public const int info = 2131230773;
			
			// aapt resource value: 0x7f080012
			public const int italic = 2131230738;
			
			// aapt resource value: 0x7f080000
			public const int item_touch_helper_previous_elevation = 2131230720;
			
			// aapt resource value: 0x7f08001a
			public const int left_drawer = 2131230746;
			
			// aapt resource value: 0x7f08000e
			public const int light = 2131230734;
			
			// aapt resource value: 0x7f080001
			public const int line1 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int line3 = 2131230722;
			
			// aapt resource value: 0x7f080014
			public const int linearLayout = 2131230740;
			
			// aapt resource value: 0x7f08002e
			public const int media_actions = 2131230766;
			
			// aapt resource value: 0x7f080023
			public const int messageTime = 2131230755;
			
			// aapt resource value: 0x7f08001b
			public const int messagebubble_layout = 2131230747;
			
			// aapt resource value: 0x7f080008
			public const int none = 2131230728;
			
			// aapt resource value: 0x7f080013
			public const int normal = 2131230739;
			
			// aapt resource value: 0x7f080038
			public const int notification_background = 2131230776;
			
			// aapt resource value: 0x7f080031
			public const int notification_main_column = 2131230769;
			
			// aapt resource value: 0x7f080030
			public const int notification_main_column_container = 2131230768;
			
			// aapt resource value: 0x7f08001f
			public const int radioButtonNo = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int radioButtonYes = 2131230750;
			
			// aapt resource value: 0x7f080024
			public const int recyclerView1 = 2131230756;
			
			// aapt resource value: 0x7f08001d
			public const int rgChoice = 2131230749;
			
			// aapt resource value: 0x7f080037
			public const int right_icon = 2131230775;
			
			// aapt resource value: 0x7f080032
			public const int right_side = 2131230770;
			
			// aapt resource value: 0x7f08000a
			public const int standard = 2131230730;
			
			// aapt resource value: 0x7f08002d
			public const int status_bar_latest_event_content = 2131230765;
			
			// aapt resource value: 0x7f080027
			public const int switchOnOff = 2131230759;
			
			// aapt resource value: 0x7f080003
			public const int text = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int text2 = 2131230724;
			
			// aapt resource value: 0x7f080026
			public const int textView2 = 2131230758;
			
			// aapt resource value: 0x7f080033
			public const int time = 2131230771;
			
			// aapt resource value: 0x7f080005
			public const int title = 2131230725;
			
			// aapt resource value: 0x7f08001c
			public const int tvMessage = 2131230748;
			
			// aapt resource value: 0x7f080016
			public const int tvPassword = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int tvUsername = 2131230741;
			
			// aapt resource value: 0x7f08000b
			public const int wide = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060001
			public const int cancel_button_image_alpha = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int status_bar_notification_info_maxnum = 2131099650;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_navigation_drawer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dashboard_row_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int drawer_list_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_dashboard = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_planet = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int fragment_settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_action = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_action_tombstone = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_media_action = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_media_cancel_action = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_big_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_big_media_custom = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media_narrow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_big_media_narrow_custom = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_custom_big = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_icon_group = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_lines_media = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_media = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_media_custom = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_part_chronometer = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int notification_template_part_time = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int sample_dashboard_item = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int navigation_drawer = 2131492864;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050018
			public const int action_refresh = 2131034136;
			
			// aapt resource value: 0x7f050014
			public const int app_name = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int app_not_available = 2131034137;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_enable_button = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_title = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_button = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_text = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_title = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_unknown_issue = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_unsupported_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_title = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_text = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_wear_update_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_open_on_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_signin_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text_long = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int drawer_close = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int drawer_open = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int gcm_defaultSenderId = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int intro_message = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int navigationdraweractivity_description = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int navigationdraweractivity_title = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int settings = 2131034139;
			
			// aapt resource value: 0x7f050011
			public const int status_bar_notification_info_overflow = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f09000c
			public const int AppTheme = 2131296268;
			
			// aapt resource value: 0x7f090005
			public const int TextAppearance_Compat_Notification = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int TextAppearance_Compat_Notification_Info = 2131296262;
			
			// aapt resource value: 0x7f090000
			public const int TextAppearance_Compat_Notification_Info_Media = 2131296256;
			
			// aapt resource value: 0x7f09000b
			public const int TextAppearance_Compat_Notification_Line2 = 2131296267;
			
			// aapt resource value: 0x7f090004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int TextAppearance_Compat_Notification_Media = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int TextAppearance_Compat_Notification_Time = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int TextAppearance_Compat_Notification_Time_Media = 2131296258;
			
			// aapt resource value: 0x7f090008
			public const int TextAppearance_Compat_Notification_Title = 2131296264;
			
			// aapt resource value: 0x7f090003
			public const int TextAppearance_Compat_Notification_Title_Media = 2131296259;
			
			// aapt resource value: 0x7f09000d
			public const int Theme_Base = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int Theme_Sample = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int Widget = 2131296271;
			
			// aapt resource value: 0x7f090009
			public const int Widget_Compat_NotificationActionContainer = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int Widget_Compat_NotificationActionText = 2131296266;
			
			// aapt resource value: 0x7f090010
			public const int Widget_SampleContentContainer = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int Widget_SampleDashboard_Grid = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int Widget_SampleDashboard_Item = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int Widget_SampleDashboard_Item_Description = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int Widget_SampleDashboard_Item_Title = 2131296276;
			
			// aapt resource value: 0x7f090011
			public const int Widget_SampleMessage = 2131296273;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 6
			public const int RecyclerView_fastScrollEnabled = 6;
			
			// aapt resource value: 9
			public const int RecyclerView_fastScrollHorizontalThumbDrawable = 9;
			
			// aapt resource value: 10
			public const int RecyclerView_fastScrollHorizontalTrackDrawable = 10;
			
			// aapt resource value: 7
			public const int RecyclerView_fastScrollVerticalThumbDrawable = 7;
			
			// aapt resource value: 8
			public const int RecyclerView_fastScrollVerticalTrackDrawable = 8;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
